# Build stage
FROM node:16 AS build
WORKDIR /app
COPY package.json yarn.lock ./
COPY frontend/package.json ./frontend/
RUN yarn install --frozen-lockfile
COPY frontend ./frontend
RUN yarn workspace frontend build

# Production stage
FROM nginx:alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]